### ISSUE TITLE
Can't open files on mobile

### ISSUE THREAD

**Issue by MesaBlack** [bigboisixty9/wadviewer#1]
I clicked "upload files" on mobile, and it's stuck at the dropping files screen. Could you let me know if you'll adapt it to mobile? Thanks

**Comment by MesaBlack** [comment]
I.e. lead from computer, expanding from simply drag and drop

**Comment by bigboisixty9** [comment]
Hi, I think it should be updated to work in mobile now with this commit https://github.com/bigboisixty9/wadviewer/commit/7f91e9bede85b37f1a3d92f5fedf38c0e1d8026a 

Tested on my android

**Comment by MesaBlack** [comment]
Nope. Make it open the files app upon taping the upload button

**Comment by bigboisixty9** [comment]
Leaving this open until we all good on the upload.

**Comment by MesaBlack** [comment]
Open files app on mobile as well
