### ISSUE TITLE
Suggestion: Github topics

### ISSUE THREAD

**Issue by MesaBlack** [bigboisixty9/wadviewer#5]
Valve
Half-Life
Half-Life 1
Goldsrc
Wad file
Wad viewer

**Comment by bigboisixty9** [comment]
Agreed. Added but modified according to github topic rules as follows:

Valve
HalfLife
HalfLife1
Goldsrc
Wadfile
Wadviewer

**Comment by bigboisixty9** [comment]
Oops, you're right. Fixed it now.
